ChatApplication/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html")),
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('register/', include('account.urls')),
    path('', include("django.contrib.auth.urls")),
]

account/urls.py
from django.urls import path, re_path

from .views import RegisterView

app_name = 'account'
urlpatterns = [
    path("", RegisterView),
]

chat/urls.py
from django.urls import path, re_path

from .views import ThreadView, InboxView, thread_list_view, search_list_view

app_name = 'chat'
urlpatterns = [
    path("", thread_list_view),
    path("search/", search_list_view),
    re_path(r"^(?P<username>[\w.@+-]+)/", ThreadView.as_view()),
]

account/models.py
from django.db import models

# Create your models here.

chat/models.py
from django.db import models

from django.conf import settings
from django.db import models
from django.db.models import Q


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username):
        # gets the thread/room or creates a new one
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                        first=user, 
                        second=user2
                    )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    # model for the creation of the thread/room
    first        = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second       = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    updated      = models.DateTimeField(auto_now=True)
    timestamp    = models.DateTimeField(auto_now_add=True)
    
    objects      = ThreadManager()

    # this creates the roomname as a number
    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    # used to generate the room name
    @property
    def roomname(self):
        roomname = f"Chat room between {self.first} and {self.second}\n"
        return roomname


class ChatMessage(models.Model):
    # base model of the messages
    thread      = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user        = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message     = models.TextField()
    timestamp   = models.DateTimeField(auto_now_add=True)

account/forms.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):

    email = forms.EmailField()

    class Meta:
        model   = User
        fields  = ["username", "email", "password1", "password2"]

chat/forms.py
from django import forms

# basic form for taking in text
class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )
            

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import RegisterForm

# Form for creation of a new user
def RegisterView(reponse):
    if reponse.method == "POST":
        form = RegisterForm(reponse.POST)
        if form.is_valid():
            form.save()
        return redirect("/")
    else:
        form = RegisterForm()

    context = {"form": form}
    return render(reponse, 'account/register.html', context)

chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic.edit import FormMixin
from django.contrib.auth.models import User

from django.views.generic import DetailView, ListView

from .forms import ComposeForm
from .models import Thread, ChatMessage


class InboxView(LoginRequiredMixin, ListView):
    # currently a generic view
    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)


class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    # view in charge of the chat threads
    template_name = 'chat/thread.html'
    form_class = ComposeForm
    success_url = './'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        # responsible for retriving the thread or 404 it
        other_username  = self.kwargs.get("username")
        obj, created    = Thread.objects.get_or_new(self.request.user, other_username)
        if obj == None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        # handling the post of a message rejects if not authorized
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

# searches for the user specified and takes the searcher to that chat room
def search_list_view(request, *args, **kwargs):
    template_name = 'chat/search.html'
    form_class = ComposeForm
    search_id = request.POST.get('search_user')
    context = {}
    if search_id != None:
        new_url = f'http://127.0.0.1:8000/chat/{search_id}'
        return redirect(new_url)
    
    return render(request, template_name, context)

# lists all chats the user is in 
def thread_list_view(request, *args, **kwargs):
    template_name = 'chat/inbox.html'
    queryset = Thread.objects.by_user(request.user)
    context = {"object_list": queryset}
    return render(request, template_name, context)

chat/templates/chat/inbox.html
{% extends "base.html" %}
{% block header %}
<h1 class='p-0 m-0'>Your Chat Rooms</h1>
{% endblock %}
{% block content %}
{% for chat in object_list %}
    <ul>
        {% if user == chat.first %}
            <li><a href={{ chat.second }}>{{ chat.roomname }}</a></li>
        {% else %}
            <li><a href={{ chat.first }}>{{ chat.roomname }}</a></li>
        {% endif %}
    </ul>
{% endfor %}

{% endblock %}

chat/templates/chat/search.html
{% extends "base.html" %}

{% block header %}
<h1 class='p-0 m-0'>User Search</h1>
{% endblock %}

{% block content %}
<div class="search-bar mt-sm-2 mr-2">
    <form method="POST" name='search_user'>
        {% csrf_token %}
        <input type="text" class="form-control" name="search_user" id="search_user" placeholder="Search...">
        <input type='submit' class='btn btn-primary'/>
    </form>
</div>
{% endblock %}

chat/templates/chat/thread.html
{% extends "base.html" %}
{% load static %}
{% block header %}
<h1 class='p-0 m-0'>Chat Room with {% if user != object.first %}{{ object.first }}{% else %}{{ object.second }}{% endif %}</h1>
{% endblock %}
{% block content %}
<div id='chat-container'>
<ul id='chat-items'>
{% for chat in object.chatmessage_set.all %}

<li><b>{{ chat.user }}:</b> {{ chat.message }}</li>

{% endfor %}
</ul>
</div>

<form id='form' method='POST'> {% csrf_token %}
    <input type='hidden' id='myUsername' value='{{ user.username }}'>
{{form.as_p}}
<input type='submit' class='btn btn-primary'/>
</form>


{% endblock %}

{% block script %}
<script src="{% static 'reconnecting-websocket.js' %}"></script>
<script>
    var loc = window.location
    var formData = $("#form")
    var msgInput = $("#id_message")
    var chatHolder = $("#chat-items")
    var me = $("#myUsername").val()
    var wsStart = 'ws://'
    if (loc.protocol== 'https:'){
        wsStart = 'wss://'
    }

    var endpoint = wsStart + loc.host + loc.pathname 
    var socket = new ReconnectingWebSocket(endpoint)

    // what the socket does with a message
    socket.onmessage = function(e){
        var chatDataMsg = JSON.parse(e.data)
        chatHolder.append("<li>" + "<b>" + chatDataMsg.username + ": " + "</b>" + chatDataMsg.message + "</li>")
    }
    
    socket.onopen = function(e){
        // sends the data back as json data and resets the input
        formData.submit(function(event){
            event.preventDefault()
            var msgText = msgInput.val()
            var finalData = {
                'message': msgText,
            }
            socket.send(JSON.stringify(finalData))
            formData[0].reset()
        })
    }


</script>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}Chat Room{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
</head>
<body>
    
    <div class="sidenav">
        <a href="/">Home</a>
        <a href="/chat">Chat</a>
        <a href="/chat/search">Search</a>
        <a href="/login">Login</a>
        <a href="/logout">Logout</a>
    </div>

    <div class="main">
        <div class='container'>
            <div class='row border-bottom my-3 py-3'>
                <div class='col'>
                    {% block header %}

                    {% endblock %}
                </div>
            </div>
            {% block content %}
            {% endblock %}
        </div>
            {% include 'js.html' %}
            {% block script %}
            {% endblock %}
    </div>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block header %}
<h1 class='p-0 m-0'>Chat Application</h1>
{% endblock %}
{% block content %}
<p class='lead'>Welcome to the home page of that chat application.</p>
<p>Please use the side bar to register, log in, search for users, and chat with people!</p>
{% endblock %}

templates/js.html
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>